services:
  blog-app:
    image: ahmedbenaissa2004/blog_api:1.0.0
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    container_name: blog-app
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:3000'
    env_file: .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@blog-postgres:5432/blog_db?schema=public
      REDIS_URL: redis://blog-redis:6379
    depends_on:
      blog-postgres:
        condition: service_healthy
      blog-redis:
        condition: service_healthy
    networks:
      - blog-network

  blog-postgres:
    image: postgres:16-alpine
    container_name: blog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-blog_db}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - blog-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - blog-network

  blog-redis:
    image: redis:7-alpine
    container_name: blog-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - blog-redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - blog-network

volumes:
  blog-postgres-data:
  blog-redis-data:

networks:
  blog-network:
    driver: bridge
